packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/eslint": ^8.38.0

  "@types/node": ^20.14.13

  tsup: 8.2.0

  "@testing-library/jest-dom": "^6.5.0"
  "@testing-library/react": "^16.0.1"
  "vitest": "2.1.2"
  "jsdom": "25.0.1"
  "@vitest/coverage-v8": "2.1.2"

  vite: ^5.4.8
  "vite-tsconfig-paths": "^5.0.1"
  "@vitejs/plugin-react": "^4.2.1"

  react: ^18.3.0
  "@types/react": ^18.3.0
  react-dom: ^18.3.0
  "@types/react-dom": ^18.3.0

  "react-icons": "5.4.0"

  "i18next": "^23.14.0"
  "react-i18next": "^15.0.1"

  "react-hook-form": "^7.52.2"
  "@hookform/resolvers": "^3.10.0"
  "wouter": "^3.3.1"

  "zustand": "^4.5.4"

  "clsx": "^2.1.1"
  "autoprefixer": "10.4.20"
  "postcss": "8.4.47"
  "postcss-import": "16.1.0"
  "tailwindcss": "3.4.13"

  "@chromatic-com/storybook": "^3.2.3"
  "storybook": "^8.4.7"
  "@storybook/addon-essentials": "^8.4.7"
  "@storybook/addon-interactions": "^8.4.7"
  "@storybook/addon-toolbars": "^8.4.7"
  "@storybook/blocks": "^8.4.7"
  "@storybook/react": "^8.4.7"
  "@storybook/react-vite": "^8.4.7"
  "@storybook/test": "^8.4.7"

  "uuid": "^10.0.0"
  "@types/uuid": "^10.0.0"

  "zod": "^3.24.1"
  "zod-i18n-map": "^2.27.0"

  "@apollo/server": "4.11.3"
  "@as-integrations/fastify": "2.1.1"
  "graphql": "16.10.0"
  "graphql-tag": "^2.12.6"
  "@graphql-codegen/add": "5.0.3"
  "@graphql-codegen/cli": "5.0.4"
  "@graphql-codegen/import-types-preset": "3.0.0"
  "@graphql-codegen/typescript": "4.1.3"
  "@graphql-codegen/typescript-operations": "4.4.1"
  "@graphql-codegen/typescript-react-apollo": "4.3.2"
  "@graphql-codegen/typescript-resolvers": "4.4.2"
  "@graphql-tools/load-files": "^7.0.1"
  "@graphql-tools/merge": "^9.0.17"
  "@graphql-tools/schema": "^10.0.16"

  "pino-pretty": "13.0.0"
  "close-with-grace": "2.2.0"
  "dotenv": "16.4.7"

  "fastify": "^4.28.1"
  "fastify-plugin": "^4.5.1"
  "fastify-type-provider-zod": "^2.0.0"
  "@fastify/autoload": "^5.10.0"
  "@fastify/compress": "^7.0.3"
  "@fastify/cors": "^9.0.1"
  "@fastify/error": "^4.0.0"
  "@fastify/helmet": "^11.1.1"
  "@fastify/rate-limit": "^9.1.0"
  "@fastify/swagger": "^8.15.0"
  "@fastify/swagger-ui": "^4.1.0"
  "@fastify/under-pressure": "^8.5.1"
  "mongoose": "8.7.1"
  "mongodb-memory-server": "^10.1.0"

  "@aws-sdk/client-ses": "^3.670.0"
  "nodemailer": "^6.9.15"
  "@types/nodemailer": "^6.4.16"

  "jwt-decode": "^4.0.0"
  "jsonwebtoken": "^9.0.2"
  "@types/jsonwebtoken": "^9.0.7"
  "bcrypt": "^5.1.1"
  "@types/bcrypt": "^5.0.2"