packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/eslint": ^8.38.0

  "@types/node": ^20.14.13

  tsup: 8.2.0

  "@testing-library/jest-dom": "^6.5.0"
  "@testing-library/react": "^16.0.1"
  "vitest": "2.1.2"
  "jsdom": "25.0.1"
  "@vitest/coverage-v8": "2.1.2"

  vite: ^5.4.8
  "vite-tsconfig-paths": "^5.0.1"
  "@vitejs/plugin-react": "^4.2.1"

  react: ^18.3.0
  "@types/react": ^18.3.0
  react-dom: ^18.3.0
  "@types/react-dom": ^18.3.0

  "react-icons": "5.4.0"

  "i18next": "^23.14.0"
  "react-i18next": "^15.0.1"

  "react-hook-form": "^7.52.2"
  "wouter": "^3.3.1"

  "zustand": "^4.5.4"

  "clsx": "^2.1.1"
  "autoprefixer": "10.4.20"
  "postcss": "8.4.47"
  "postcss-import": "16.1.0"
  "tailwindcss": "3.4.13"

  "@chromatic-com/storybook": "^3.2.3"
  "storybook": "^8.4.7"
  "@storybook/addon-essentials": "^8.4.7"
  "@storybook/addon-interactions": "^8.4.7"
  "@storybook/addon-toolbars": "^8.4.7"
  "@storybook/blocks": "^8.4.7"
  "@storybook/react": "^8.4.7"
  "@storybook/react-vite": "^8.4.7"
  "@storybook/test": "^8.4.7"